/* ---- Careers (Mythras Core) ---- */

const CAREERS = [
  {
    name: "Agent",
    standard_skills: [
      "Conceal",
      "Deceit",
      "Evade",
      "Insight",
      "Perception",
      "Stealth",
    ],
    professional_skills: [
      "Culture (any)",
      "Disguise",
      "Language (any)",
      "Sleight",
      "Streetwise",
      "Survival",
      "Track",
    ],
  },

  {
    name: "Alchemist",
    standard_skills: [
      "Customs",
      "Endurance",
      "First Aid",
      "Insight",
      "Locale",
      "Perception",
      "Willpower",
    ],
    professional_skills: [
      "Commerce",
      "Craft (Alchemy)",
      "Healing",
      "Language (any)",
      "Literacy",
      "Lore (acids)",
      "Lore (narcotics)",
      "Lore (poisons)",
    ],
  },

  {
    name: "Beast Handler",
    standard_skills: [
      "Drive",
      "Endurance",
      "First Aid",
      "Influence",
      "Locale",
      "Ride",
      "Willpower",
    ],
    professional_skills: [
      "Commerce",
      "Craft (Animal Husbandry)",
      "Healing",
      "Lore (Specific Animal)",
      "Survival",
      "Teach (Specific Animal)",
      "Track",
    ],
  },

  {
    name: "Courtesan",
    standard_skills: [
      "Customs",
      "Dance",
      "Deceit",
      "Influence",
      "Insight",
      "Perception",
      "Sing",
    ],
    professional_skills: [
      "Art (any)",
      "Courtesy",
      "Culture (any)",
      "Gambling",
      "Language (any)",
      "Musicianship",
      "Seduction",
    ],
  },

  {
    name: "Courtier",
    standard_skills: [
      "Customs",
      "Dance",
      "Deceit",
      "Influence",
      "Insight",
      "Locale",
      "Perception",
    ],
    professional_skills: [
      "Art (any)",
      "Bureaucracy",
      "Courtesy",
      "Culture (any)",
      "Language (any)",
      "Lore (any)",
      "Oratory",
    ],
  },

  {
    name: "Crafter",
    standard_skills: [
      "Brawn",
      "Drive",
      "Influence",
      "Insight",
      "Locale",
      "Perception",
      "Willpower",
    ],
    professional_skills: [
      "Art (any)",
      "Commerce",
      "Craft (Any Primary)",
      "Craft (Any Secondary)",
      "Engineering",
      "Mechanisms",
      "Streetwise",
    ],
  },

  {
    name: "Entertainer",
    standard_skills: [
      "Athletics",
      "Brawn",
      "Dance",
      "Deceit",
      "Influence",
      "Insight",
      "Sing",
    ],
    professional_skills: [
      "Acrobatics",
      "Acting",
      "Oratory",
      "Musicianship",
      "Seduction",
      "Sleight",
      "Streetwise",
    ],
  },

  {
    name: "Farmer",
    standard_skills: [
      "Athletics",
      "Brawn",
      "Drive",
      "Endurance",
      "Locale",
      "Perception",
      "Ride",
    ],
    professional_skills: [
      "Commerce",
      "Craft (any)",
      "Lore (Agriculture)",
      "Lore (Animal Husbandry)",
      "Navigation",
      "Track",
      "Survival",
    ],
  },

  {
    name: "Fisher",
    standard_skills: [
      "Athletics",
      "Boating",
      "Endurance",
      "Locale",
      "Perception",
      "Stealth",
      "Swim",
    ],
    professional_skills: [
      "Commerce",
      "Craft (any)",
      "Lore (Specific Catch)",
      "Lore (Specific Catch)",
      "Navigation",
      "Seamanship",
      "Survival",
    ],
  },

  {
    name: "Herder",
    standard_skills: [
      "Endurance",
      "First Aid",
      "Insight",
      "Locale",
      "Perception",
      "Ride",
    ],
    professional_skills: [
      "Commerce",
      "Craft (Animal Husbandry)",
      "Healing",
      "Navigation",
      "Musicianship",
      "Survival",
      "Track",
    ],
  },

  {
    name: "Hunter",
    standard_skills: [
      "Athletics",
      "Endurance",
      "Locale",
      "Perception",
      "Ride",
      "Stealth",
    ],
    professional_skills: [
      "Commerce",
      "Craft (Hunting Related)",
      "Lore (Regional Creatures)",
      "Lore (Specific Species)",
      "Mechanisms",
      "Navigation",
      "Survival",
      "Track",
    ],
  },

  {
    name: "Merchant",
    standard_skills: [
      "Boating",
      "Drive",
      "Deceit",
      "Insight",
      "Influence",
      "Locale",
      "Ride",
    ],
    professional_skills: [
      "Commerce",
      "Courtesy",
      "Culture (any)",
      "Language (any)",
      "Navigation",
      "Seamanship",
      "Streetwise",
    ],
  },

  {
    name: "Miner",
    standard_skills: [
      "Athletics",
      "Brawn",
      "Endurance",
      "Locale",
      "Perception",
      "Sing",
      "Willpower",
    ],
    professional_skills: [
      "Commerce",
      "Craft (Mining)",
      "Engineering",
      "Lore (Minerals)",
      "Mechanisms",
      "Navigation (Underground)",
      "Survival",
    ],
  },

  {
    name: "Mystic",
    standard_skills: [
      "Athletics",
      "Endurance",
      "Evade",
      "Insight",
      "Perception",
      "Willpower",
    ],
    professional_skills: [
      "Art (any)",
      "Folk Magic",
      "Literacy",
      "Lore (any)",
      "Meditation",
      "Musicianship",
      "Mysticism",
    ],
  },

  {
    name: "Official",
    standard_skills: [
      "Customs",
      "Deceit",
      "Influence",
      "Insight",
      "Locale",
      "Perception",
      "Willpower",
    ],
    professional_skills: [
      "Bureaucracy",
      "Commerce",
      "Courtesy",
      "Language (any)",
      "Literacy",
      "Lore (any)",
      "Oratory",
    ],
  },

  {
    name: "Physician",
    standard_skills: [
      "Dance",
      "First Aid",
      "Influence",
      "Insight",
      "Locale",
      "Sing",
      "Willpower",
    ],
    professional_skills: [
      "Commerce",
      "Craft (Medical Speciality)",
      "Healing",
      "Language (any)",
      "Literacy",
      "Lore (Alchemical Speciality)",
      "Streetwise",
    ],
  },

  {
    name: "Priest",
    standard_skills: [
      "Customs",
      "Dance",
      "Deceit",
      "Influence",
      "Insight",
      "Locale",
      "Willpower",
    ],
    professional_skills: [
      "Bureaucracy",
      "Devotion (specific faith)",
      "Folk Magic",
      "Literacy",
      "Lore (any)",
      "Oratory",
    ],
  },

  {
    name: "Sailor",
    standard_skills: [
      "Athletics",
      "Boating",
      "Brawn",
      "Endurance",
      "Locale",
      "Swim",
    ],
    professional_skills: [
      "Craft (Relevant Specialty)",
      "Culture (any)",
      "Language (any)",
      "Lore (any)",
      "Navigation",
      "Seamanship",
      "Survival",
    ],
  },

  {
    name: "Scholar",
    standard_skills: [
      "Customs",
      "Influence",
      "Insight",
      "Locale",
      "Native Tongue",
      "Perception",
      "Willpower",
    ],
    professional_skills: [
      "Culture (any)",
      "Language (any)",
      "Literacy",
      "Lore (Primary Speciality)",
      "Lore (Secondary Speciality)",
      "Oratory",
      "Teach",
    ],
  },

  {
    name: "Scout",
    standard_skills: [
      "Athletics",
      "Endurance",
      "First Aid",
      "Perception",
      "Stealth",
      "Swim",
    ],
    professional_skills: [
      "Culture (any)",
      "Healing",
      "Language (any)",
      "Lore (any)",
      "Navigation",
      "Survival",
      "Track",
    ],
  },

  {
    name: "Shaman",
    standard_skills: [
      "Customs",
      "Dance",
      "Deceit",
      "Influence",
      "Insight",
      "Locale",
      "Willpower",
    ],
    professional_skills: [
      "Binding (specific tradition)",
      "Folk Magic",
      "Healing",
      "Lore (any)",
      "Oratory",
      "Sleight",
      "Trance",
    ],
  },

  {
    name: "Sorcerer",
    standard_skills: [
      "Customs",
      "Deceit",
      "Influence",
      "Insight",
      "Locale",
      "Perception",
      "Willpower",
    ],
    professional_skills: [
      "Folk Magic",
      "Invocation (specific school)",
      "Language (any)",
      "Literacy",
      "Lore (any)",
      "Shaping",
      "Sleight",
    ],
  },

  {
    name: "Thief",
    standard_skills: [
      "Athletics",
      "Deceit",
      "Evade",
      "Insight",
      "Perception",
      "Stealth",
    ],
    professional_skills: [
      "Acting",
      "Commerce",
      "Disguise",
      "Lockpicking",
      "Mechanisms",
      "Sleight",
      "Streetwise",
    ],
  },

  {
    name: "Warrior",
    standard_skills: [
      "Athletics",
      "Brawn",
      "Endurance",
      "Evade",
      "Unarmed",
    ],
    professional_skills: [
      "Craft (any)",
      "Engineering",
      "Gambling",
      "Lore (Military History)",
      "Lore (Strategy and Tactics)",
      "Oratory",
      "Survival",
    ],
  },
];
