const PRIORITY_SKILLS = [
  Athletics, Brawn, Combat Style, Endurance, Evade, Insight, Willpower
];

const STANDARD_SKILLS = [
  "Athletics", "Boating", "Brawn", "Conceal", "Customs", "Dance", "Deceit",
  "Drive", "Endurance", "Evade", "First Aid", "Influence", "Insight",
  "Locale", "Native Tongue", "Perception", "Ride", "Sing", "Stealth",
  "Swim", "Unarmed", "Willpower",
];

// base stat formulas (root skill name => [stat1, stat2])
const SKILL_BASE_FORMULAS = {
  // Standard
  Athletics: ["STR", "DEX"],
  Boating: ["STR", "CON"],
  Brawn: ["STR", "SIZ"],
  Conceal: ["DEX", "POW"],
  Customs: ["INT", "INT"],
  Dance: ["DEX", "CHA"],
  Deceit: ["INT", "CHA"],
  Drive: ["DEX", "POW"],
  Endurance: ["CON", "CON"],
  Evade: ["DEX", "DEX"],
  "First Aid": ["DEX", "INT"],
  Influence: ["CHA", "CHA"],
  Insight: ["INT", "POW"],
  Locale: ["INT", "INT"],
  "Native Tongue": ["INT", "CHA"],
  Perception: ["INT", "POW"],
  Ride: ["DEX", "POW"],
  Sing: ["POW", "CHA"],
  Stealth: ["DEX", "INT"],
  Swim: ["STR", "CON"],
  Unarmed: ["STR", "DEX"],
  Willpower: ["POW", "POW"],

  // Professional
  Acrobatics: ["STR", "DEX"],
  Acting: ["CHA", "CHA"],
  Art: ["POW", "CHA"],
  Binding: ["POW", "CHA"],
  Bureaucracy: ["INT", "INT"],
  Computers: ["INT", "INT"],
  Commerce: ["INT", "CHA"],
  Courtesy: ["INT", "CHA"],
  Craft: ["DEX", "INT"],
  Culture: ["INT", "INT"],
  Demolitions: ["INT", "POW"],
  Devotion: ["POW", "CHA"],
  Disguise: ["INT", "CHA"],
  Engineering: ["INT", "INT"],
  Exhort: ["INT", "CHA"],
  "Folk Magic": ["POW", "CHA"],
  Gambling: ["INT", "POW"],
  Healing: ["INT", "POW"],
  Invocation: ["POW", "CHA"],
  Language: ["INT", "CHA"],
  Literacy: ["INT", "POW"],
  Lockpicking: ["DEX", "DEX"],
  Lore: ["INT", "INT"],
  Mechanisms: ["DEX", "INT"],
  Meditation: ["INT", "CON"],
  Musicianship: ["DEX", "CHA"],
  Mysticism: ["POW", "CON"],
  Navigation: ["INT", "POW"],
  Oratory: ["POW", "CHA"],
  Seamanship: ["INT", "CON"],
  Seduction: ["INT", "CHA"],
  Shaping: ["INT", "POW"],
  Sleight: ["DEX", "CHA"],
  Streetwise: ["POW", "CHA"],
  Survival: ["CON", "POW"],
  Teach: ["INT", "CHA"],
  Track: ["INT", "CON"],
  Trance: ["POW", "CON"],
};
